/**
 * Created by sjzhang on 2016/11/16.
 */
'use strict';

export const ActionTypes = {
	RECEIVE_PRIVATE_MESSAGE: "RECEIVE_PRIVATE_MESSAGE",
	SET_PRIVATE_MESSAGE_READ: "SET_PRIVATE_MESSAGE_READ",
	RECEIVE_FRIENDS_USER_INFO: "RECEIVE_FRIENDS_USER_INFO"
};